debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.example.projectboard: debug
    org.springframework.web.servlet: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: jong1228
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
